- hosts: all
  sudo: yes
  tasks:
      - name: Restart server
      shell: " sleep 3; shutdown -r now"
      async: 1
      poll: 0
      ignore_errors: true
      - name: Wait for the server to finish rebooting
      sudo: no
      local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300
