---
- hosts: all
  become: yes
  tasks:
# Restart the sipxcom service no matter what
#- service:
#    name: sipexecs
#    state: restarted
- name: stop nginx service 
  service: name=sipexecs state=restarted 
